name: Feature Request
description: 새로운 기능을 요청할 때 사용해주세요.
title: "[Feat] "
labels: ["✨ Feature"]
body:
  - type: input
    id: parentKey
    attributes:
      label: '상위 작업 Ticket Number'
      description: '상위 작업의 Ticket Number를 기입해주세요 (없다면 비워두세요)'
      placeholder: 'KAN-00'
    validations:
      required: false

  - type: input
    id: feature_summary
    attributes:
      label: "⚒️ 구현할 기능"
      description: "어떤 기능을 구현하고 싶은지 적어주세요."
      placeholder: "ex) 회원 가입 기능 구현"
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: "🎯 기능이 필요한 이유"
      description: "왜 이 기능이 필요한지 설명해주세요."
      placeholder: "이 기능이 필요한 이유를 간략하게 적어주세요."

  - type: textarea
    id: plan
    attributes:
      label: "✨ 구현 계획"
      description: "어떤 방식으로 구현할 계획인지 적어주세요."
      placeholder: "구현 계획을 자세히 적어주세요."

  - type: textarea
    id: details
    attributes:
      label: "📝 작업 상세 내용"
      description: "기능 구현에 필요한 체크 리스트를 작성해주세요."
      value: |
        - [ ] 내용 1
        - [ ] 내용 2
    validations:
      required: true

  - type: input
    id: startdate
    attributes:
      label: "🗓️ 시작일"
      description: "개발 시작일을 입력해주세요."
      placeholder: "yyyy-mm-dd"  # 날짜 형식 안내
    validations:
      required: true

  - type: input
    id: enddate
    attributes:
      label: "🗓️ 종료일"
      description: "개발 종료일을 입력해주세요."
      placeholder: "yyyy-mm-dd"  # 날짜 형식 안내
    validations:
      required: true

  - type: textarea
    id: references
    attributes:
      label: "🌱 나누고 싶은 점"
      description: "기능 관련 나누고 싶은 내용을 작성해주세요."
      placeholder: "참고한 자료나 의견을 공유해주세요."
